### ISSUE TITLE
Binary package not found to download

### ISSUE THREAD

**Issue by rafacouto** [flathub/com.anydesk.Anydesk#134]
```
        ID                           Branch          Op         Remote          Download
 1. [✗] com.anydesk.Anydesk          stable          i          flathub         1.0 kB / 18.0 MB

Error: While downloading https://download.anydesk.com/linux/anydesk-6.3.0-amd64.tar.gz: Server returned status 404: Not Found
error: Failed to install com.anydesk.Anydesk: While downloading https://download.anydesk.com/linux/anydesk-6.3.0-amd64.tar.gz: 
Server returned status 404: Not Found
```

**Comment by rafacouto** [comment]
This could be related or give further info about the problem:

https://buildbot.flathub.org/#/builders/6/builds/107812

**Comment by der-eismann** [comment]
Thanks for reporting! The anydesk page is a mess, when I download the latest package from their site it's from this URL:
https://download.anydesk.com/linux/anydesk-6.3.1-amd64.tar.gz
However the index of `https://download.anydesk.com/linux/` doesn't show any 6.3.1 entries, so the extra-data-checker didn't automatically post the update. Instead the existing links lead to a 404, probably removed all of them due to their code signing issue.
